---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r, echo = TRUE}
data <- read.csv("activity.csv")
summary(data)
```


## What is mean total number of steps taken per day?

```{r, echo = TRUE}
meanDay2 <- with(data, tapply(steps, date, sum))

hist(meanDay2, 
        xlab = "Steps", 
        ylab = " ", 
        main = "Mean total number of steps taken per day",
        col = "blue")
```

*Mean and median*
```{r, echo = TRUE}
mean(meanDay2, na.rm = TRUE)
median(meanDay2, na.rm = TRUE)
```


## What is the average daily activity pattern?
```{r, echo = TRUE}
meanInterval2 <- with(data, tapply(steps, interval, mean, na.rm = TRUE))

forP <- data.frame(unique(data$interval), meanInterval2)
ind = 0
iMax <- max(forP[, 2]) 
for (i in seq_along(unique(data$interval)))
        if (forP[, 2][i] == iMax) ind <- forP[, 1][i]

plot(forP[, 1], forP[, 2], type = "l")
points(ind, iMax, col = "red")

infS1 <- paste("Interval number", ind, sep = " ")
infS2 <- paste(ceiling(iMax), "steps", sep = " ")
        
text(ind, iMax, paste(infS1, infS2, sep = "\n"), cex=0.5, pos=4, col="red")

paste(infS1, infS2, sep = ", ")
```

## Imputing missing values

```{r, echo = TRUE}
# 1. count missing values
paste("Total number of missing values:", sum(is.na(data$steps) == TRUE), sep = " ")

# 2. 3. Imputting day averages instead of missing values
meanDay <- replace(meanDay2, is.na(meanDay2), 0)

data2 <- data
for (i in 1:length(data2[, 2])) 
        if (is.na(data2[ , 1][i])) 
                data2[, 1][i] <- meanDay[data2[, 2][i]]
#Any NAs?
summary(data2)
# Thanks, no!

# 4.
meanDay3 <- with(data2, tapply(steps, date, sum))

hist(meanDay3, 
        xlab = "Steps", 
        ylab = " ", 
        main = "Mean total number of steps taken per day\n (without NAs)",
        col = "green")

mean(meanDay3, na.rm = TRUE)
median(meanDay3, na.rm = TRUE)
```

## Are there differences in activity patterns between weekdays and weekends?

```{r, echo = FALSE}
library(lattice)
library(dplyr)

Sys.setlocale("LC_ALL", 'en_US.UTF-8')
```

```{r, echo = TRUE}
data2$wdFactor <- weekdays(as.Date(data2$date), abbreviate = TRUE)
data2$wdFactor <- replace(data2$wdFactor, data2$wdFactor %in% c("Sun", "Sat"), "weekend")
data2$wdFactor <- replace(data2$wdFactor, data2$wdFactor %in% c("Mon", "Tue", "Wed", "Thu", "Fri"), "weekday")

data3 <- group_by(data2, interval, wdFactor) %>% summarise_each(funs(mean))

xyplot(steps ~ interval | wdFactor, data = data3, layout = c(1, 2), type = "l", col = "blue")

```